CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251007085921_CreateUsers') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserName" text NOT NULL,
        "Email" text NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251007085921_CreateUsers') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251007085921_CreateUsers', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251007131629_Rooms_FieldMapping_Init') THEN
    CREATE TABLE "Rooms" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "RoomType" character varying(13) NOT NULL,
        "NumberOfChairs" integer DEFAULT 0,
        CONSTRAINT "PK_Rooms" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251007131629_Rooms_FieldMapping_Init') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251007131629_Rooms_FieldMapping_Init', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013061251_AddBookingsAndBedrooms') THEN
    ALTER TABLE "Rooms" DROP CONSTRAINT "PK_Rooms";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013061251_AddBookingsAndBedrooms') THEN
    ALTER TABLE "Rooms" RENAME TO rooms;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013061251_AddBookingsAndBedrooms') THEN
    ALTER TABLE rooms RENAME COLUMN "ID" TO "Id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013061251_AddBookingsAndBedrooms') THEN
    ALTER TABLE rooms RENAME COLUMN "NumberOfChairs" TO number_of_chairs;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013061251_AddBookingsAndBedrooms') THEN
    ALTER TABLE rooms RENAME COLUMN "RoomType" TO room_type;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013061251_AddBookingsAndBedrooms') THEN
    ALTER TABLE rooms ADD number_of_beds integer DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013061251_AddBookingsAndBedrooms') THEN
    ALTER TABLE rooms ADD CONSTRAINT "PK_rooms" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013061251_AddBookingsAndBedrooms') THEN
    CREATE TABLE bookings (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoomId" integer NOT NULL,
        "StartTime" timestamp with time zone NOT NULL,
        "EndTime" timestamp with time zone NOT NULL,
        "Title" character varying(200),
        "RoomId1" integer,
        CONSTRAINT "PK_bookings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_bookings_rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES rooms ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_bookings_rooms_RoomId1" FOREIGN KEY ("RoomId1") REFERENCES rooms ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013061251_AddBookingsAndBedrooms') THEN
    CREATE INDEX ix_booking_room_time ON bookings ("RoomId", "StartTime", "EndTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013061251_AddBookingsAndBedrooms') THEN
    CREATE INDEX "IX_bookings_RoomId1" ON bookings ("RoomId1");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013061251_AddBookingsAndBedrooms') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251013061251_AddBookingsAndBedrooms', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013093255_UserAddPhone') THEN
    ALTER TABLE "Users" ADD "Phone" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013093255_UserAddPhone') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251013093255_UserAddPhone', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118140003_InitialCreate') THEN
    ALTER TABLE bookings DROP CONSTRAINT "FK_bookings_rooms_RoomId1";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118140003_InitialCreate') THEN
    DROP INDEX "IX_bookings_RoomId1";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118140003_InitialCreate') THEN
    ALTER TABLE bookings DROP COLUMN "RoomId1";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118140003_InitialCreate') THEN
    ALTER TABLE "Users" ALTER COLUMN "UserName" TYPE character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118140003_InitialCreate') THEN
    ALTER TABLE "Users" ALTER COLUMN "Email" TYPE character varying(320);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251118140003_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251118140003_InitialCreate', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251124090615_AddBookingTable') THEN

                    INSERT INTO rooms ("Id", "Name", number_of_chairs, room_type)
                    VALUES (1, 'Conference Room A', 20, 'Meetingroom')
                    ON CONFLICT ("Id") DO NOTHING;

                    INSERT INTO rooms ("Id", "Name", number_of_chairs, room_type)
                    VALUES (2, 'Conference Room B', 15, 'Meetingroom')
                    ON CONFLICT ("Id") DO NOTHING;

                    INSERT INTO rooms ("Id", "Name", number_of_chairs, room_type)
                    VALUES (3, 'Board Room', 10, 'Meetingroom')
                    ON CONFLICT ("Id") DO NOTHING;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251124090615_AddBookingTable') THEN

                    INSERT INTO rooms ("Id", "Name", number_of_beds, room_type)
                    VALUES (4, 'Room 101', 1, 'Bedroom')
                    ON CONFLICT ("Id") DO NOTHING;

                    INSERT INTO rooms ("Id", "Name", number_of_beds, room_type)
                    VALUES (5, 'Room 102', 2, 'Bedroom')
                    ON CONFLICT ("Id") DO NOTHING;

                    INSERT INTO rooms ("Id", "Name", number_of_beds, room_type)
                    VALUES (6, 'Room 103', 2, 'Bedroom')
                    ON CONFLICT ("Id") DO NOTHING;

                    INSERT INTO rooms ("Id", "Name", number_of_beds, room_type)
                    VALUES (7, 'Suite 201', 3, 'Bedroom')
                    ON CONFLICT ("Id") DO NOTHING;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251124090615_AddBookingTable') THEN

                    DO $$
                    DECLARE
                        seq_name text;
                    BEGIN
                        -- für Identity/Serial die Sequenz ermitteln und auf MAX(Id) setzen
                        SELECT pg_get_serial_sequence('rooms','Id') INTO seq_name;
                        IF seq_name IS NOT NULL THEN
                            EXECUTE format('SELECT setval(''%s'', (SELECT COALESCE(MAX("Id"), 1) FROM rooms))', seq_name);
                        END IF;
                    END$$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251124090615_AddBookingTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251124090615_AddBookingTable', '9.0.9');
    END IF;
END $EF$;
COMMIT;

