// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostGresAPI.Data;

#nullable disable

namespace PostGresAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208140111_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostGresAPI.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "StartTime", "EndTime")
                        .HasDatabaseName("ix_booking_room_time");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("PostGresAPI.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("room_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("rooms", (string)null);

                    b.HasDiscriminator<string>("room_type").HasValue("Room");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PostGresAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PostGresAPI.Models.Bedroom", b =>
                {
                    b.HasBaseType("PostGresAPI.Models.Room");

                    b.Property<int>("NumberOfBeds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("number_of_beds");

                    b.HasDiscriminator().HasValue("Bedroom");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Name = "Room 101",
                            NumberOfBeds = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Room 102",
                            NumberOfBeds = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Room 103",
                            NumberOfBeds = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Suite 201",
                            NumberOfBeds = 3
                        });
                });

            modelBuilder.Entity("PostGresAPI.Models.Meetingroom", b =>
                {
                    b.HasBaseType("PostGresAPI.Models.Room");

                    b.Property<int>("NumberOfChairs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("number_of_chairs");

                    b.HasDiscriminator().HasValue("Meetingroom");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Conference Room A",
                            NumberOfChairs = 20
                        },
                        new
                        {
                            Id = 2,
                            Name = "Conference Room B",
                            NumberOfChairs = 15
                        },
                        new
                        {
                            Id = 3,
                            Name = "Board Room",
                            NumberOfChairs = 10
                        });
                });

            modelBuilder.Entity("PostGresAPI.Models.Booking", b =>
                {
                    b.HasOne("PostGresAPI.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PostGresAPI.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
